// Generated by gencpp from file path_finding/Path.msg
// DO NOT EDIT!


#ifndef PATH_FINDING_MESSAGE_PATH_H
#define PATH_FINDING_MESSAGE_PATH_H

#include <ros/service_traits.h>


#include <path_finding/PathRequest.h>
#include <path_finding/PathResponse.h>


namespace path_finding
{

struct Path
{

typedef PathRequest Request;
typedef PathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Path
} // namespace path_finding


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::path_finding::Path > {
  static const char* value()
  {
    return "6b486115390018cf18c53ea7f1a78dca";
  }

  static const char* value(const ::path_finding::Path&) { return value(); }
};

template<>
struct DataType< ::path_finding::Path > {
  static const char* value()
  {
    return "path_finding/Path";
  }

  static const char* value(const ::path_finding::Path&) { return value(); }
};


// service_traits::MD5Sum< ::path_finding::PathRequest> should match 
// service_traits::MD5Sum< ::path_finding::Path > 
template<>
struct MD5Sum< ::path_finding::PathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::path_finding::Path >::value();
  }
  static const char* value(const ::path_finding::PathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::path_finding::PathRequest> should match 
// service_traits::DataType< ::path_finding::Path > 
template<>
struct DataType< ::path_finding::PathRequest>
{
  static const char* value()
  {
    return DataType< ::path_finding::Path >::value();
  }
  static const char* value(const ::path_finding::PathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::path_finding::PathResponse> should match 
// service_traits::MD5Sum< ::path_finding::Path > 
template<>
struct MD5Sum< ::path_finding::PathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::path_finding::Path >::value();
  }
  static const char* value(const ::path_finding::PathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::path_finding::PathResponse> should match 
// service_traits::DataType< ::path_finding::Path > 
template<>
struct DataType< ::path_finding::PathResponse>
{
  static const char* value()
  {
    return DataType< ::path_finding::Path >::value();
  }
  static const char* value(const ::path_finding::PathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PATH_FINDING_MESSAGE_PATH_H
